homepage:
  path: /
  defaults: { _controller: ClientBundle:Homepage:homepage}
userchooseLangage:
  path: /userchooselangage/{langue}
  defaults: { _controller: ClientBundle:Homepage:chooseLangage} 
shop:
  path: /shop
  defaults: { _controller: ClientBundle:Shop:shop}   
getaddress:
  path: /getaddress
  defaults: { _controller: ClientBundle:User:getAddress} 
setclient:
  path: /setclient
  defaults: { _controller: ClientBundle:Client:setClient}
  requirements :
    _method: POST
setclientaddress:
  path: /setclientaddress
  defaults: { _controller: ClientBundle:Client:setClientAddress}
  requirements :
    _method: POS    

#

facture:
  path: /facture
  defaults: { _controller: ClientBundle:Facturation:facture}    
#
#  User Functions
#   
userchoosecategory:
  path: /userchoosecategory
  defaults: { _controller: ClientBundle:Homepage:chooseCategory} 
usermodelsearch:
  path: /usermodelsearch
  defaults: { _controller: ClientBundle:Homepage:modelsearch} 
userchoosemodel:
  path: /userchoosemodel/{category}
  defaults: { _controller: ClientBundle:Homepage:chooseModel} 
usermodel: 
   path: /usermodel/
   defaults: { _controller: ClientBundle:Homepage:model} 
userbasket:
  path: /userbasket/  
  defaults: { _controller: ClientBundle:Homepage:basket} 
getclient:
  path: /getclient/
  defaults: { _controller: ClientBundle:Client:getClient}
validateclient:
  path: /validate/{token}
  defaults: { _controller: ClientBundle:Client:validateClient}
lostPassword:
  path: /lostpassword/
  defaults: { _controller: ClientBundle:Client:lostPassword}
passwordclient:
  path: /password/{token}
  defaults: { _controller: ClientBundle:Client:passwordClient}    
contact:
  path: /contact/   
  defaults: { _controller: ClientBundle:Contact:contact}
  
user_product_homepage:
  path: /user_product_homepage
  defaults: { _controller: ClientBundle:Product:choice} 
user_product_modelsearch:
  path: /user_product_modelsearch
  defaults: { _controller: ClientBundle:Product:modelSearch}
user_product_modelset:
  path: /user_product_modelset
  defaults: { _controller: ClientBundle:Product:setModel}
user_product_setcategory:
  path: /user_product_setcategory
  defaults: { _controller: ClientBundle:Product:setCategory} 
  requirements:
     _method: POST  
user_product_set:
  path: /user_product_set
  defaults: { _controller: ClientBundle:Product:set}        
####
user_basket:
  path: /user_basket
  defaults: { _controller: ClientBundle:Basket:home}      
user_basket_list:
  path: /user_basket_list
  defaults: { _controller: ClientBundle:Basket:setList} 
user_basket_present:
  path: /user_basket_present
  defaults: { _controller: ClientBundle:Basket:present}
user_basket_set:
  path: /user_basket_set
  defaults: { _controller: ClientBundle:Basket:basketSet}   
  requirements:
     _method: POST 
user_basket_name:
  path: /user_basket_name/{id}
  defaults: { _controller: ClientBundle:Basket:name}     
user_basket_get:
  path: /user_basket_get/{id}
  defaults: { _controller: ClientBundle:Basket:basketGet}
user_order_summary:
  path: /user_order_summary/{id}
  defaults: { _controller: ClientBundle:Order:summary} 
user_order_payment:
  path: /user_order_payment/{id}
  defaults: { _controller: ClientBundle:Order:payment}
user_order_bill:
  path: /user_order_bill/{id}
  defaults: { _controller: ClientBundle:Order:bill}           