services:
#    client.example:
#        class: ClientBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  app.validate_address:
        class: ClientBundle\Validator\Address\ValidateAddress
  app.validate_clientname:
        class: ClientBundle\Validator\Client\ValidateClientName  
  app.contains_postal_code_validator:
        class: ClientBundle\Validator\Address\ContainsPostalCodeValidator
        tags:
            - { name: validator.constraint_validator } 
  app.pseudocontact:
        class:     AppBundle\PseudoClasses\PseudoContact
        arguments: []
         