services:
#    client.example:
#        class: ClientBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  app.validate_address:
        class: ClientBundle\Validator\Address\ValidateAddress
  app.validate_clientname:
        class: ClientBundle\Validator\Client\ValidateClientName  
  app.contains_postal_code_validator:
        class: ClientBundle\Validator\Address\ContainsPostalCodeValidator
        tags:
            - { name: validator.constraint_validator } 
  app.product:
       class:     ClientBundle\Service\Product 
          
  app.html2pdf:
       class:     ClientBundle\Service\HtmlToPDF     
             
  app.image:
        class: ClientBundle\Service\Image
        arguments:
            $targetDir: '%app.blog_photos%'  
        tags:
          - { name: app.extension } 
  app.historic:
       class: ClientBundle\Service\HistoricGest
       arguments: [ "@doctrine.orm.entity_manager" ]
       tags:
           - { name: app.extension }
           