bmstation:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
client:
    resource: "@ClientBundle/Resources/config/routing.yml"
user:
    resource: "@UserBundle/Resources/config/routing.yml"
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"    

    

