<?php

namespace ClientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository {
	
	public function findInOrder()
	{
	$qb = $this->createQueryBuilder('c');
	$qb ->where('c.validate is null');
	$qb	->orderBy('c.date', 'DESC');
	
	
	$query = $qb->getQuery();
	$contacts = $query->getResult();
	
	return($contacts);
	}
}