<?php

namespace ClientBundle\Repository;

/**
 * HistoricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllHistoric($client){
		
		$qb = $this->createQueryBuilder('h')
		->Join('h.client', 'c')
		->where('c=:client') 
		->setparameter('client',$client);
		$query=$qb->getQuery();
		$ret=$query->getResult();
		
		return $ret;
		
	}
}
