<?php

namespace ClientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	/**
	 * Récupère en une transaction toutes les informations d'un client
	 * 
	 * @param unknown $client
	 * @return unknown
	 */
	public function findAllValues($client){
		$return=array();
		
		
		
		$qb = $this->createQueryBuilder('c')
		->Join('c.deliveryAddress', 'a')
		->Join('c.user', 'u')
		->addSelect('a')
		->addSelect('u')
		->where('c.id=:client')
		->setparameter('client',$client);
		$query = $qb->getQuery();
		$ret=$query->getResult();
		
		if($ret){
                    $newClient=$ret[0];    
	            $cl=$newClient->toArray();
                }
                else
                    $cl=null;
                
		
		return $cl;
	}
	public function findByEmail($email) {
		
		$qb = $this->createQueryBuilder('c')
		->Join('c.user', 'u')
		->where('u.email=:email')
		->setparameter('email',$email);
		$query=$qb->getQuery();
		$ret=$query->getResult();
		if($ret)
		return $ret[0];
		else return null;
	}
	
}