<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	public function findbyCategory($category){
		
		$qb = $this->createQueryBuilder('a');
		$qb	->where("a.category= :category")
		->orderBy('a.name', 'ASC')
		->setParameter('category', $category);
		
		$query = $qb->getQuery();
		$products = $query->getResult();
		return $products;
	}
	
	public function findbyModel($category){
		
		$qb = $this->createQueryBuilder('c')
		->Join();
		$qb	->where("a.category= :category")
		->orderBy('a.name', 'ASC')
		->setParameter('category', $category);
		
		$query = $qb->getQuery();
		$products = $query->getResult();
		return $products;
	}
	
	public function findByName($name){	
	
		$qb = $this->createQueryBuilder('a');
		$qb -> where ("a.name=:name")
		->setParameter('name',$name);
		
		$query = $qb->getQuery();
		$product=$query->getResult();
		return $product;
	}
	
		
}
