services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
 app.form.registration:
        class: UserBundle\Form\RegistrationFormType
        tags:
            - { name: form.type }
 
